project:
  type: website
  resources:
   - assets/*

website:
  title: "2025 SWPO striped marlin assessment meeting"
  reader-mode: false
  site-url: "https://N-DucharmeBarth-NOAA.github.io/2025-swpo-mls-meeting" 
  repo-url: "https://github.com/N-DucharmeBarth-NOAA/2025-swpo-mls-meeting"
  repo-actions: [source, issue]
  search: true
  back-to-top-navigation: true
  bread-crumbs: false
  sidebar:
    collapse-level: 1
    style: "floating"
    search: true
    tools:
      - icon: github
        href: https://github.com/N-DucharmeBarth-NOAA/2025-swpo-mls-meeting
    contents: 
      - text: "Home"
        file: index.qmd
      - section: "WCPFC-SC report"
        contents:
        - text: "HTML"
          file: assets/noaa-spc-model-meeting-report.qmd
        - text: "PDF"
          file: assets/noaa-spc-model-meeting-report.pdf
      - text: "Repository instructions"
        file: assets/instructions.qmd
      - text: "PAW investigations"
        file: assets/paw-investigations.qmd
      - section: "Support"
        contents:
        - text: "Submit an issue"
          href: https://github.com/N-DucharmeBarth-NOAA/2025-swpo-mls-meeting/issues/new/choose
  page-footer:
    center: 
      - text: "NOAA Fisheries | SPC | 2025"
    background: primary

format: 
  html:
    toc: true
    toc-expand: false
    theme:
      - default
      - assets/customizations/website-custom.scss
